services:
  - type: web
    name: song-showdown
    runtime: node
    plan: free
    buildCommand: ""
    startCommand: node server.js
    envVars:
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
